# Generated by Django 5.0.6 on 2024-06-20 12:41

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField(validators=[book.models.validate_date])),
                ('isbn', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
